version: '3.5'
services:
  ebank-postgresql:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: "singh"
      POSTGRES_PASSWORD: "singh"
      POSTGRES_DB: "ebank"
    ports:
    - 5432:5432

  ebank-test-postgresql:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: "singh"
      POSTGRES_PASSWORD: "singh"
      POSTGRES_DB: "ebank_test"
    ports:
      - 5441:5432